[package]
name = "wall-e"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[dependencies]
image = "0.24.7"
lazy_static = "1.4.0"
nalgebra = "0.32.3"
obj = "0.10.2"
rand = "0.8.5"
encase = "0.6.1"
